# Generated by Django 6.0.4 on 2026-04-20 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('is_player', models.BooleanField(default=False)),
                ('is_leader', models.BooleanField(default=False)),
                ('is_wanderer', models.BooleanField(default=False)),
                ('is_dead', models.BooleanField(default=False)),
                ('can_merge', models.BooleanField(default=True)),
                ('combat_skill', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=0)),
                ('max_speed', models.IntegerField(default=4)),
                ('scouting', models.IntegerField(default=0)),
                ('resource_generation', models.IntegerField(default=1)),
                ('ration_limit', models.IntegerField(default=5)),
                ('rations', models.IntegerField(default=0)),
                ('famine_streak', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('drive', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Hex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('terrain_type', models.CharField(choices=[('plains', 'Plains'), ('forest', 'Forest'), ('mountain', 'Mountain'), ('swamp', 'Swamp'), ('desert', 'Desert'), ('coast', 'Coast')], default='plains', max_length=20)),
                ('resources', models.IntegerField(default=0)),
                ('weather', models.CharField(choices=[('fair', 'Fair'), ('unpleasant', 'Unpleasant'), ('inclement', 'Inclement'), ('extreme', 'Extreme'), ('catastrophic', 'Catastrophic')], default='fair', max_length=20)),
                ('encounter_likelihood', models.IntegerField(default=0)),
                ('player_explored', models.BooleanField(default=False)),
                ('player_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('do_players_know', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='maps/')),
                ('hex_size', models.IntegerField(default=40)),
                ('origin_x', models.IntegerField(default=0)),
                ('origin_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_amount', models.IntegerField(default=5)),
                ('hex_resource_tick_modifier', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'World Settings',
                'verbose_name_plural': 'World Settings',
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_player_faction', models.BooleanField(default=False)),
                ('is_gm_faction', models.BooleanField(default=False)),
                ('speed', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=50)),
                ('technology', models.IntegerField(default=20)),
                ('technology_max', models.IntegerField(default=50)),
                ('resources', models.IntegerField(default=50)),
                ('agreeableness', models.IntegerField(default=0)),
                ('combat_skill', models.IntegerField(default=50)),
                ('scouting', models.IntegerField(default=1)),
                ('theology', models.IntegerField(default=50)),
                ('current_action', models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve')], max_length=20, null=True)),
                ('last_action', models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve')], max_length=20, null=True)),
                ('population_trend_override', models.IntegerField(blank=True, null=True)),
                ('famine_streak', models.IntegerField(default=0)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_factions', to='world.character')),
                ('current_hex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factions', to='world.hex')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_factions', to='world.hex')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='world.faction'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_hex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='world.hex'),
        ),
        migrations.AddField(
            model_name='character',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_destinations', to='world.hex'),
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.ManyToManyField(blank=True, to='world.item'),
        ),
        migrations.AddField(
            model_name='character',
            name='knowledge',
            field=models.ManyToManyField(blank=True, to='world.knowledge'),
        ),
        migrations.AddField(
            model_name='hex',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hexes', to='world.map'),
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_type', models.CharField(choices=[('dungeon', 'Dungeon'), ('village', 'Village'), ('ruin', 'Ruin'), ('stash', 'Stash'), ('monster_base', 'Monster Base')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('difficulty', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('technology_max_modifier', models.IntegerField(default=1)),
                ('monster_type', models.CharField(blank=True, default='', max_length=100)),
                ('player_explored', models.BooleanField(default=False)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to='world.faction')),
                ('hex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='world.hex')),
                ('items', models.ManyToManyField(blank=True, to='world.item')),
                ('knowledge', models.ManyToManyField(blank=True, to='world.knowledge')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(choices=[('madness', 'Madness'), ('black_death', 'Black Death'), ('the_runs', 'The Runs'), ('ravenous', 'Ravenous'), ('bad_food', 'Bad Food'), ('restless', 'Restless')], max_length=20)),
                ('duration_days_remaining', models.IntegerField()),
                ('effect_value', models.IntegerField(default=0)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='world.faction')),
            ],
            options={
                'unique_together': {('faction', 'disease_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='hex',
            unique_together={('map', 'row', 'col')},
        ),
        migrations.CreateModel(
            name='HexTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrain_type', models.CharField(max_length=20)),
                ('resources', models.IntegerField()),
                ('weather', models.CharField(choices=[('fair', 'Fair'), ('unpleasant', 'Unpleasant'), ('inclement', 'Inclement'), ('extreme', 'Extreme'), ('catastrophic', 'Catastrophic')], max_length=20)),
                ('encounter_likelihood', models.IntegerField()),
                ('player_explored', models.BooleanField()),
                ('player_visible', models.BooleanField()),
                ('hex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='world.hex')),
                ('points_of_interest', models.ManyToManyField(blank=True, to='world.pointofinterest')),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hex_ticks', to='world.tick')),
            ],
            options={
                'unique_together': {('tick', 'hex')},
            },
        ),
        migrations.CreateModel(
            name='FactionTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mobile', models.BooleanField()),
                ('speed', models.IntegerField()),
                ('population', models.IntegerField()),
                ('technology', models.IntegerField()),
                ('technology_max', models.IntegerField()),
                ('resources', models.IntegerField()),
                ('agreeableness', models.IntegerField()),
                ('combat_skill', models.IntegerField()),
                ('scouting', models.IntegerField()),
                ('theology', models.IntegerField()),
                ('famine_streak', models.IntegerField()),
                ('action', models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve')], max_length=20, null=True)),
                ('dice_roll', models.IntegerField(blank=True, null=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='world.faction')),
                ('current_hex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.hex')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.hex')),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_ticks', to='world.tick')),
            ],
            options={
                'unique_together': {('tick', 'faction')},
            },
        ),
        migrations.CreateModel(
            name='CharacterTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rations', models.IntegerField()),
                ('famine_streak', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('is_dead', models.BooleanField()),
                ('is_wanderer', models.BooleanField()),
                ('action', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='world.character')),
                ('current_hex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.hex')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.hex')),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_ticks', to='world.tick')),
            ],
            options={
                'unique_together': {('tick', 'character')},
            },
        ),
    ]
