# Generated by Django 6.0.4 on 2026-04-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_alter_faction_combat_skill_alter_faction_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='player_visible',
            field=models.BooleanField(default=False),
        ),
    ]
