# Generated by Django 6.0.4 on 2026-04-20 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_pointofinterest_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='age',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='faction',
            name='current_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='last_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='factiontick',
            name='action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speed', models.IntegerField(default=0)),
                ('max_speed', models.IntegerField(default=4)),
                ('resource_generation', models.IntegerField(default=1)),
                ('current_action', models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search')], max_length=20, null=True)),
                ('last_action', models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search')], max_length=20, null=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='parties', to='world.character')),
                ('current_hex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='world.hex')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_destinations', to='world.hex')),
                ('faction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to='world.faction')),
            ],
        ),
        migrations.CreateModel(
            name='PartyTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search')], max_length=20, null=True)),
                ('last_action', models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search')], max_length=20, null=True)),
                ('current_hex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.hex')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.hex')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='world.party')),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_ticks', to='world.tick')),
            ],
            options={
                'unique_together': {('tick', 'party')},
            },
        ),
    ]
