# Generated by Django 6.0.4 on 2026-04-20 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_pointofinterest_age_alter_faction_current_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partytick',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='worldsettings',
            name='current_tick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.tick'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='current_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='last_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='factiontick',
            name='action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='current_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='last_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partytick',
            name='action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partytick',
            name='last_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore')], max_length=20, null=True),
        ),
    ]
