# Generated by Django 6.0.4 on 2026-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_partytick_notes_worldsettings_current_tick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='color',
            field=models.CharField(default='#89b4fa', max_length=7),
        ),
    ]
