# Generated by Django 6.0.4 on 2026-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_faction_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='next_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faction',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
