# Generated by Django 6.0.4 on 2026-04-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_faction_next_action_faction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='age',
            field=models.IntegerField(choices=[(1, 'Age of Magic'), (2, 'Age of Artifice'), (3, 'Age of Despair'), (4, 'Age of Dying')], default=4),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='age',
            field=models.IntegerField(choices=[(1, 'Age of Magic'), (2, 'Age of Artifice'), (3, 'Age of Despair'), (4, 'Age of Dying')], default=4),
        ),
    ]
