# Generated by Django 6.0.4 on 2026-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_knowledge_age_alter_pointofinterest_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
