# Generated by Django 6.0.4 on 2026-04-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_faction_is_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='related_knowledge',
            field=models.ManyToManyField(blank=True, to='world.knowledge'),
        ),
    ]
