# Generated by Django 6.0.4 on 2026-04-23 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_knowledge_related_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='map',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='world.map'),
            preserve_default=False,
        ),
    ]
