# Generated by Django 6.0.4 on 2026-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_knowledge_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hex',
            name='terrain_type',
            field=models.CharField(choices=[('plains', 'Plains'), ('forest', 'Forest'), ('mountain', 'Mountain'), ('swamp', 'Swamp'), ('desert', 'Desert'), ('coast', 'Coast'), ('ocean', 'Ocean')], default='plains', max_length=20),
        ),
    ]
