# Generated by Django 6.0.4 on 2026-04-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_alter_hex_terrain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='knowledge',
            field=models.ManyToManyField(blank=True, related_name='factions', to='world.knowledge'),
        ),
    ]
