# Generated by Django 6.0.4 on 2026-05-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_faction_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='map',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to='world.map'),
        ),
    ]
