# Generated by Django 6.0.4 on 2026-05-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0015_alter_faction_current_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='fog_of_war',
            field=models.BooleanField(default=True),
        ),
    ]
