# Generated by Django 6.0.4 on 2026-05-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0016_map_fog_of_war'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='player_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='party',
            name='supplies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faction',
            name='current_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('rest', 'Rest')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='last_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('rest', 'Rest')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='next_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('rest', 'Rest')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='factiontick',
            name='action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('rest', 'Rest')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='current_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('rest', 'Rest')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='last_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('rest', 'Rest')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partytick',
            name='action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('rest', 'Rest')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partytick',
            name='last_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('rest', 'Rest')], max_length=20, null=True),
        ),
    ]
