# Generated by Django 6.0.4 on 2026-05-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0017_party_player_count_party_supplies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hex',
            name='has_roads',
            field=models.BooleanField(default=False),
        ),
    ]
