# Generated by Django 6.0.4 on 2026-05-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0018_hex_has_roads'),
    ]

    operations = [
        migrations.AddField(
            model_name='hex',
            name='has_rivers',
            field=models.BooleanField(default=False),
        ),
    ]
