# Generated by Django 6.0.4 on 2026-05-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0019_hex_has_rivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='tracks_supplies',
            field=models.BooleanField(default=True),
        ),
    ]
