# Generated by Django 6.0.4 on 2026-05-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0020_party_tracks_supplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='poi_type',
            field=models.CharField(choices=[('dungeon', 'Dungeon'), ('village', 'Village'), ('ruin', 'Ruin'), ('stash', 'Stash'), ('monster_base', 'Monster Base'), ('general', 'General')], max_length=20),
        ),
    ]
