# Generated by Django 6.0.4 on 2026-05-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0021_alter_pointofinterest_poi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_type',
            field=models.CharField(choices=[('regional', 'Regional'), ('city', 'City')], default='regional', max_length=20),
        ),
        migrations.AddField(
            model_name='map',
            name='sub_tick',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partytick',
            name='sub_tick',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
