# Generated by Django 6.0.4 on 2026-05-13 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0022_map_map_type_map_sub_tick_partytick_sub_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='hex',
            name='can_enter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hex',
            name='linked_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_hexes', to='world.map'),
        ),
        migrations.AlterField(
            model_name='hex',
            name='terrain_type',
            field=models.CharField(choices=[('plains', 'Plains'), ('forest', 'Forest'), ('mountain', 'Mountain'), ('swamp', 'Swamp'), ('desert', 'Desert'), ('coast', 'Coast'), ('ocean', 'Ocean'), ('city', 'City')], default='plains', max_length=20),
        ),
    ]
