# Generated by Django 6.0.4 on 2026-05-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0023_hex_can_enter_hex_linked_map_alter_hex_terrain_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldsettings',
            name='current_tick',
        ),
        migrations.AddField(
            model_name='map',
            name='current_tick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.tick'),
        ),
    ]
