# Generated by Django 6.0.4 on 2026-05-13 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0024_remove_worldsettings_current_tick_map_current_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='map',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='world.map'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tick',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='tick',
            unique_together={('map', 'number')},
        ),
    ]
