# Generated by Django 6.0.4 on 2026-05-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0025_tick_map_alter_tick_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='player_actions_locked',
            field=models.BooleanField(default=False),
        ),
    ]
