# Generated by Django 6.0.4 on 2026-05-14 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0026_map_player_actions_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('is_published', models.BooleanField(default=False)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='world.map')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
