# Generated by Django 6.0.4 on 2026-05-14 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0027_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factions', to='world.galleryimage'),
        ),
    ]
