# Generated by Django 6.0.4 on 2026-05-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_faction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='allowed_hexes',
            field=models.ManyToManyField(blank=True, related_name='restricted_factions', to='world.hex'),
        ),
        migrations.AddField(
            model_name='faction',
            name='movement_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
