# Generated by Django 6.0.4 on 2026-06-18 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0030_alter_faction_leader_remove_charactertick_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_count', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('resource_generation', models.IntegerField()),
                ('supplies', models.IntegerField()),
                ('tracks_supplies', models.BooleanField()),
                ('current_action', models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('rest', 'Rest')], max_length=20, null=True)),
                ('last_action', models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('trade', 'Trade'), ('merge', 'Merge'), ('battle', 'Battle'), ('train', 'Train'), ('craft', 'Craft'), ('delve', 'Delve'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('rest', 'Rest')], max_length=20, null=True)),
                ('current_hex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.hex')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.hex')),
                ('map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_baseline', to='world.map')),
            ],
        ),
        migrations.CreateModel(
            name='FactionBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('population', models.IntegerField()),
                ('technology', models.IntegerField()),
                ('technology_max', models.IntegerField()),
                ('resources', models.IntegerField()),
                ('agreeableness', models.IntegerField()),
                ('combat_skill', models.IntegerField()),
                ('current_hex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.hex')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.hex')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='world.faction')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_baselines', to='world.map')),
            ],
            options={
                'unique_together': {('map', 'faction')},
            },
        ),
        migrations.CreateModel(
            name='HexBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrain_type', models.CharField(max_length=20)),
                ('resources', models.IntegerField()),
                ('weather', models.CharField(choices=[('fair', 'Fair'), ('unpleasant', 'Unpleasant'), ('inclement', 'Inclement'), ('extreme', 'Extreme'), ('catastrophic', 'Catastrophic')], max_length=20)),
                ('encounter_likelihood', models.IntegerField()),
                ('player_explored', models.BooleanField()),
                ('player_visible', models.BooleanField()),
                ('hex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='world.hex')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hex_baselines', to='world.map')),
            ],
            options={
                'unique_together': {('map', 'hex')},
            },
        ),
    ]
