# Generated by Django 6.0.4 on 2026-06-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0031_partybaseline_factionbaseline_hexbaseline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hexbaseline',
            name='terrain_type',
        ),
        migrations.RemoveField(
            model_name='hextick',
            name='terrain_type',
        ),
    ]
