# Generated by Django 6.0.4 on 2026-06-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0032_remove_hexbaseline_terrain_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hexbaseline',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hexbaseline',
            name='hex',
        ),
        migrations.RemoveField(
            model_name='hexbaseline',
            name='map',
        ),
        migrations.RemoveField(
            model_name='partybaseline',
            name='current_hex',
        ),
        migrations.RemoveField(
            model_name='partybaseline',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='partybaseline',
            name='map',
        ),
        migrations.DeleteModel(
            name='FactionBaseline',
        ),
        migrations.DeleteModel(
            name='HexBaseline',
        ),
        migrations.DeleteModel(
            name='PartyBaseline',
        ),
    ]
