# Generated by Django 6.0.4 on 2026-06-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0033_alter_hexbaseline_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
    ]
