# Generated by Django 6.0.4 on 2026-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0034_party_is_lost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hex',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='hextick',
            name='weather',
        ),
        migrations.AddField(
            model_name='map',
            name='weather',
            field=models.CharField(choices=[('fair', 'Fair'), ('overcast', 'Overcast'), ('inclement', 'Inclement'), ('extreme', 'Extreme'), ('catastrophic', 'Catastrophic')], default='fair', max_length=20),
        ),
    ]
