# Generated by Django 6.0.4 on 2026-07-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0035_remove_hex_weather_remove_hextick_weather_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='is_player_faction',
        ),
        migrations.RemoveField(
            model_name='party',
            name='faction',
        ),
    ]
