# Generated by Django 6.0.4 on 2026-07-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0036_remove_faction_is_player_faction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='map',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='related_knowledge',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='agreeableness',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='combat_skill',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='famine_streak',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='is_gm_faction',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='population_trend_override',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='scouting',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='technology_max',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='theology',
        ),
        migrations.RemoveField(
            model_name='factiontick',
            name='agreeableness',
        ),
        migrations.RemoveField(
            model_name='factiontick',
            name='combat_skill',
        ),
        migrations.RemoveField(
            model_name='factiontick',
            name='famine_streak',
        ),
        migrations.RemoveField(
            model_name='factiontick',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='factiontick',
            name='scouting',
        ),
        migrations.RemoveField(
            model_name='factiontick',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='factiontick',
            name='technology_max',
        ),
        migrations.RemoveField(
            model_name='factiontick',
            name='theology',
        ),
        migrations.AddField(
            model_name='faction',
            name='max_speed',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='faction',
            name='current_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('rest', 'Rest'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('delve', 'Delve')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='last_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('rest', 'Rest'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('delve', 'Delve')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='next_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('rest', 'Rest'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('delve', 'Delve')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='factiontick',
            name='action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('rest', 'Rest'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('delve', 'Delve')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='current_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('rest', 'Rest'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('delve', 'Delve')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='last_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('rest', 'Rest'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('delve', 'Delve')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partytick',
            name='action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('rest', 'Rest'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('delve', 'Delve')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partytick',
            name='last_action',
            field=models.CharField(blank=True, choices=[('supply', 'Supply'), ('travel', 'Travel'), ('rest', 'Rest'), ('search', 'Search'), ('explore', 'Explore'), ('social', 'Social'), ('delve', 'Delve')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ActiveDisease',
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
    ]
