# Generated by Django 6.0.4 on 2026-07-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0037_remove_knowledge_map_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldsettings',
            name='trade_amount',
        ),
    ]
