# Generated by Django 6.0.4 on 2026-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0038_remove_worldsettings_trade_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/'),
        ),
        migrations.AddField(
            model_name='map',
            name='reveal_mode',
            field=models.CharField(choices=[('grey_fog', 'Grey fog'), ('two_layer', 'Two-layer (NPC + detailed map)')], default='grey_fog', max_length=20),
        ),
    ]
