# Generated by Django 6.0.4 on 2026-07-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0040_faction_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hextick',
            name='points_of_interest',
        ),
        migrations.RemoveField(
            model_name='party',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='partytick',
            name='destination',
        ),
    ]
