[project]
name = "HexTick"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Josh Fink",email = "laggard12@proton.me"},
]
dependencies = [
    "django>=5.2",
    "Pillow>=10.0",
    "psycopg2-binary>=2.9",
    "django-ninja>=1.3",
    "gunicorn>=22.0",
    "redis>=7.4.0",
]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
makemigrations = {shell = "set -a && . ./.env && set +a && python backend/manage.py makemigrations"}
test = {shell = "set -a && . ./.env && set +a && USE_SQLITE=true pytest"}

[dependency-groups]
test = [
    "pytest>=9.1.1",
    "pytest-django>=4.12.0",
    "pytest-cov>=6.0.0",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "HexTick.settings"
pythonpath = ["backend"]
testpaths = ["backend/world/tests"]
