# Generated by Django 6.0.4 on 2026-04-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='combat_skill',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='faction',
            name='speed',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='faction',
            name='technology_max',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='faction',
            name='theology',
            field=models.IntegerField(default=90),
        ),
    ]
